// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.Property<DateTime>("LastModifiedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastModifiedOn");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("Isbn")
                        .IsUnique()
                        .HasDatabaseName("iX_books_isbn");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Domain.Books.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("bookId");

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("isAvailable");

                    b.Property<DateTime>("LastModifiedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastModifiedOn");

                    b.HasKey("Id")
                        .HasName("pk_bookCopies");

                    b.HasIndex("BookId")
                        .HasDatabaseName("iX_bookCopies_bookId");

                    b.ToTable("bookCopies", (string)null);
                });

            modelBuilder.Entity("Domain.Loans.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer")
                        .HasColumnName("bookCopyId");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("borrowedAt");

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dueDate");

                    b.Property<DateTime>("LastModifiedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastModifiedOn");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("memberId");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returnedAt");

                    b.HasKey("Id")
                        .HasName("pK_loans");

                    b.HasIndex("BookCopyId")
                        .HasDatabaseName("ix_loans_bookCopyId");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_loans_memberId");

                    b.HasIndex("BookCopyId", "ReturnedAt")
                        .HasDatabaseName("ix_loans_bookCopyId_returnedAt");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("firstName");

                    b.Property<DateTime>("LastModifiedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastModifiedOn");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lastName");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("membershipType");

                    b.HasKey("Id")
                        .HasName("pK_members");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("iX_members_email");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Domain.Books.BookCopy", b =>
                {
                    b.HasOne("Domain.Books.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_bookCopies_books_bookId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain.Loans.Loan", b =>
                {
                    b.HasOne("Domain.Books.BookCopy", null)
                        .WithMany()
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_loans_bookCopyId");

                    b.HasOne("Domain.Members.Member", null)
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_loans_members_memberId");
                });

            modelBuilder.Entity("Domain.Books.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
