<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Testcontainers" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Api\Api.csproj" />
      <ProjectReference Include="..\Support.SharedTests\Support.SharedTests.csproj" />
    </ItemGroup>
    
    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

</Project>